<a href="https://colab.research.google.com/github/WisdomerLee/Pytorch/blob/main/10pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Basic

In [ ]:
import numpy as np
import torch

In [ ]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
nums.shape

torch.Size([9])

In [ ]:
type(nums)

torch.Tensor

In [ ]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [ ]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
randoms = torch.rand(3,3)
randoms

tensor([[0.9144, 0.7947, 0.9317],
        [0.8769, 0.9661, 0.7663],
        [0.2554, 0.0098, 0.6422]])

In [ ]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros.size()

torch.Size([3, 3])

Operations
Pytorch 수학연산

In [ ]:
nums*3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
nums = nums.reshape((3,3))

In [ ]:
nums +nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
result = torch.add(nums, 10)

In [ ]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

View

In [ ]:
range_nums = torch.arange(9).reshape(3,3)

In [ ]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
range_nums.view(1, 9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

Slice and Index

In [ ]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
nums[1]

tensor([3, 4, 5])

In [ ]:
nums[1,1]

tensor(4)

In [ ]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [ ]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

Compile
numpy를 torch tensor로 불러오기

In [ ]:
arr = np.array([1,1,1])

In [ ]:
arr_torch = torch.from_numpy(arr)

In [ ]:
arr_torch.float()

tensor([1., 1., 1.])

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
arr_torch.to(device)

tensor([1, 1, 1], device='cuda:0', dtype=torch.int32)

In [ ]:
device

'cuda'

AutoGrad

In [ ]:
x= torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [ ]:
print(y.grad_fn)

In [ ]:
z = y*y*3
out = z.mean()

In [ ]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
out.backward()

In [ ]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
print(x.requires_grad)
print((x**2).requires_grad)

True
True


In [ ]:
# 기울기가 필요 없는 상태로 하면 테스팅이 더 빨라진다고 함..
with torch.no_grad():
    print((x**2).requires_grad)

False
