<a href="https://colab.research.google.com/github/WisdomerLee/Pytorch/blob/main/1numpybasicTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Basic

In [ ]:
import numpy as np

data type
array의 dtype을 보기

In [ ]:
arr = np.array([[1,2,3,],[5,6,7]])

In [ ]:
arr.dtype

dtype('int32')

.astype()으로 datatype을 변환 가능

In [ ]:
arr.astype('float32')

array([[1., 2., 3.],
       [5., 6., 7.]], dtype=float32)

In [ ]:
arr.astype(np.int32)

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
arr = np.array([[1,2,3], [8,0,3]], dtype=np.uint8)
arr.dtype

dtype('uint8')

In [ ]:
len(arr.shape)

2

In [ ]:
arr.shape

(2, 3)

Reshape

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr = arr.reshape([1,6])
arr.shape

(1, 6)

In [ ]:
arr = np.array([[1,2,3], [6,7,8]])
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [ ]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [ ]:
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

In [ ]:
arr = arr.reshape(3, -1)
arr.shape

(3, 2)

Random array 생성

In [ ]:
arr= np.random.randn(8,8)
arr.shape

(8, 8)

In [ ]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [ ]:
arr = arr.reshape(-1, 2,1,1,2,1,)
arr.shape

(16, 2, 1, 1, 2, 1)

Ravel : 1차원으로 늘리기... layer를 flatten할 때 같은 기능....

In [ ]:
arr.shape

(16, 2, 1, 1, 2, 1)

In [ ]:
arr = arr.ravel()
arr.shape

(64,)

In [ ]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

np.expand_dims()
값은 유지하되 차원 숫자를 늘리고 싶을 때


In [ ]:
arr.shape

(64,)

In [ ]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [ ]:
arr= np.expand_dims(np.expand_dims(arr, -1), 0)
arr.shape

(1, 1, 64, 1, 1, 1)