<a href="https://colab.research.google.com/github/WisdomerLee/Pytorch/blob/main/2_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#zeros & ones
0으로 채워진 numpy array를 만들 수 있음


In [ ]:
import numpy as np

In [ ]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zeros = np.zeros(1)
zeros

array([0.])

In [ ]:
ones = np.ones([5,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones *5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [ ]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#Index

In [ ]:
nums =[1,2,3,4,5]
nums[2:]

[3, 4, 5]

In [ ]:
nums = [1,2,3,4,[1,3,4]]
nums
nums[4]

[1, 3, 4]

In [ ]:
arr[1]

array([3, 4, 5])

In [ ]:
arr[1][2]

5

In [ ]:
arr[1,2]

5

In [ ]:
#Slicing

In [ ]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

In [ ]:
#boolean Indexing

In [ ]:
data = np.random.randn(3,3)
data

array([[-0.19342086,  0.13041938,  1.31291639],
       [ 1.25771593,  1.0812849 , -0.15381872],
       [-0.29282155, -0.3321372 , -1.27693659]])

In [ ]:
data <=0

array([[ True, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
data[data<=0] = 1

In [ ]:
data

array([[1.        , 0.13041938, 1.31291639],
       [1.25771593, 1.0812849 , 1.        ],
       [1.        , 1.        , 1.        ]])

#Broadcast
tensorflow, pytorch로 계산: broadcast의 개념도 잘 이해해야 함....
    broadcast: 연산하려는 서로 다른 두 개의 행렬의 shape가 다르고 한쪽의 차원이 같거나 값의 갯수가 한 개일 때 여러 복사를 하여 연산.

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [ ]:
#Math Function

In [ ]:
arr +10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
arr*5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [ ]:
arr+ arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
arr = np.random.randint(2, size=27).reshape(3,3,3)
arr_2 = np.random.randint(2, size =9).reshape(3,3)

In [ ]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [ ]:
print(arr), print(arr_2)

[[[1 1 0]
  [0 0 1]
  [0 0 1]]

 [[1 0 1]
  [0 0 0]
  [1 1 0]]

 [[0 0 1]
  [0 1 0]
  [1 0 1]]]
[[0 0 1]
 [0 0 1]
 [0 0 0]]


(None, None)

In [ ]:
arr * arr_2

array([[[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
np.sum(arr)

12

In [ ]:
np.sum(arr+arr_2)

18

In [ ]:
np.max(arr+arr_2)

2

In [ ]:
np.min(arr+arr_2)

0

In [ ]:
np.max(arr+arr_2, 0)

array([[1, 1, 2],
       [0, 1, 2],
       [1, 1, 1]])

In [ ]:
np.max(arr+arr_2, -1)

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [ ]:
np.sum(arr+arr_2, axis = -1)

array([[3, 2, 1],
       [3, 1, 2],
       [2, 2, 2]])

In [ ]:
np.mean(arr)

0.4444444444444444

In [ ]:
arr = np.array([1,2,6,3,5,7,1])
arr

array([1, 2, 6, 3, 5, 7, 1])

In [ ]:
np.argmax(arr) # 어레이중에 가장 큰 값을 가진 인덱스

5

In [ ]:
np.argmin(arr) #배열 중에 가장 작은 값을 가진 인덱스

0

In [ ]:
arr = np.array([3,5,6,6,3,1])

In [ ]:
np.unique(arr) #겹치는 값 빼고 숫자가 몇 종류나 있는지 확인할 때...

array([1, 3, 5, 6])