<a href="https://colab.research.google.com/github/WisdomerLee/Pytorch/blob/main/5TensorflowExamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf

Tensor 생성
[]
 list 생성

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

Array 생성
tuple이나 list 둘 다 np.array()로 array로 만들 수 있음

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr.shape

(3,)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr.shape

(2, 3)

Tensor 생성
tf.constant()
list->Tensor

In [ ]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

tf.constant()
tuple -> Tensor

In [ ]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

tf.constant()
array->Tensor

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

Tensor에 담긴 정보 확인
shape확인

In [ ]:
tensor.shape

TensorShape([3])

data type 확인
Tensor 생성할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수 있음
Data type에 따라 모델의 무게, 성능에도 영향을 줄 수 있음

In [ ]:
tensor.dtype

tf.int32

data type 정의

In [ ]:
tensor = tf.constant([1,2,3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

data type 변환
Numpy에서 astype(), TensorFlow에서는 tf.cast사용

In [ ]:
arr = np.array([1,2,3], dtype = np.float32)

In [ ]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [ ]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
tf.cast(tensor, dtype = tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

Tensor에서 Numpy 불러오기
.numpy()

In [ ]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [ ]:
Tensor에서 Numpy 불러오기
np.array()

In [ ]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

In [ ]:
type(tensor.numpy())

numpy.ndarray

난수 생성

Normal Distribution: 중심 극한 이론에 의한 연속
Uniform Distribution: 불연속, 일정
numpy에서는 normal distribution을 기본으로 생성
np.random.randn()

In [ ]:
np.random.randn(9)

array([-0.1919586 , -0.55942942,  1.76168265,  0.64019745,  0.1847585 ,
       -1.31813074,  0.84132483, -0.33494684,  0.77748812])

tf.random.normal
Tensorflow에서 Normal Distribution

In [ ]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.9117302 ,  0.07868001, -1.0871475 ],
       [-0.8064827 ,  0.3732613 , -0.67023563],
       [ 0.7110157 ,  3.8698008 ,  0.7795326 ]], dtype=float32)>

tf.random.uniform

In [ ]:
tf.random.uniform([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.34545898, 0.27375245, 0.05304146, 0.32947147],
       [0.7925961 , 0.5996934 , 0.21633434, 0.16912186],
       [0.639101  , 0.82814276, 0.41185856, 0.8688618 ],
       [0.3733816 , 0.6571517 , 0.24935746, 0.61124456]], dtype=float32)>